# -*- coding: utf-8 -*-
"""IRISclassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gcE4IxZkZ0Fmo_RnyGCu5wCkgGWQeczZ
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
iris=load_iris()

print(iris)

df=pd.DataFrame(data=iris.data,columns=iris.feature_names)

df['flower']=iris.target

print(df)

X=df.drop(columns='flower',axis=1)
Y=df['flower']

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2,stratify=Y)

scaler=StandardScaler()
scaler.fit(X)
stddata=scaler.transform(X)

XX_train,XX_test,YY_train,YY_test=train_test_split(stddata,Y,test_size=0.2,random_state=1,stratify=Y)

#models
model=LogisticRegression()
model2=svm.SVC(kernel='linear')

model.fit(X_train,Y_train)
model2.fit(XX_train,YY_train)

p1=model.predict(X_test)
p2=model.predict(XX_test)

acc=accuracy_score(p1,Y_test)

acc2=accuracy_score(p2,YY_test)

print(acc*100)
print(acc2*100)